القالب غير موجود في /ar/profile/2fa-setup/
base_django.html
طريقة الطلب:	بريد
عنوان URL للطلب:	http://7959abac-2c10-4a5c-80c9-e069d8967e39-00-r6rp5l8il9c3.pike.replit.dev/ar/profile/2fa-setup/
نسخة دجانجو:	5.2
نوع الاستثناء:	القالب غير موجود
قيمة الاستثناء:	
base_django.html
موقع الاستثناء:	/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py ، السطر 130، في إعادة الرفع
نشأت خلال:	rental.views.user_2fa_setup
ملف بايثون القابل للتنفيذ:	/nix/store/wqhkxzzlaswkj3gimqign99sshvllcg6-python-wrapped-0.1.0/bin/python3
إصدار بايثون:	3.11.10
مسار بايثون:	
['/home/runner/workspace',
 '/home/runner/workspace/.pythonlibs/bin',
 '/nix/store/lc7qv2ldzrs1aq3hbyzmbgvn0h2w26pl-sitecustomize/lib/python/site-packages',
 '/nix/store/dfg63lldbvcj207iyr9z0xw21d8ax02n-python3.11-pip-24.0/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python311.zip',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/lib-dynload',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/wblvmd5y7izx0z10d1w7ga7zc4apjxmb-python3.11-setuptools-75.1.1/lib/python3.11/site-packages',
 '/home/runner/workspace']
وقت الخادم:	الاثنين، 12 مايو 2025 16:37:35 +0000
تحليل ما بعد تحميل القالب
حاول Django تحميل هذه القوالب، بهذا الترتيب:

استخدام المحرك django:

django.template.loaders.filesystem.Loader: /home/runner/workspace/templates/base_django.html (المصدر غير موجود)
django.template.loaders.filesystem.Loader: /home/runner/workspace/rental/templates/base_django.html (المصدر غير موجود)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/admin/templates/base_django.html (المصدر غير موجود)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/auth/templates/base_django.html (المصدر غير موجود)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/crispy_bootstrap5/templates/base_django.html (المصدر غير موجود)
django.template.loaders.app_directories.Loader: /home/runner/workspace/rental/templates/base_django.html (المصدر غير موجود)
خطأ أثناء عرض القالب
في القالب /home/runner/workspace/templates/security/user_2fa_setup.html، خطأ في السطر 1

base_django.html
1	{% يمتد "base_django.html" %}