OperationalError at /ar/dashboard/custody/
no such table: rental_customerguarantee
Request Method:	GET
Request URL:	http://0d6600bd-cd28-44c5-a1ce-4bc854f89c47-00-2s4bnt31ovsut.sisko.replit.dev/ar/dashboard/custody/
Django Version:	5.2
Exception Type:	OperationalError
Exception Value:	
no such table: rental_customerguarantee
Exception Location:	/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py, line 360, in execute
Raised during:	rental.views_custody.custody_dashboard
Python Executable:	/nix/store/wqhkxzzlaswkj3gimqign99sshvllcg6-python-wrapped-0.1.0/bin/python3
Python Version:	3.11.10
Python Path:	
['/home/runner/workspace',
 '/home/runner/workspace/.pythonlibs/bin',
 '/nix/store/lc7qv2ldzrs1aq3hbyzmbgvn0h2w26pl-sitecustomize/lib/python/site-packages',
 '/nix/store/dfg63lldbvcj207iyr9z0xw21d8ax02n-python3.11-pip-24.0/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python311.zip',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/lib-dynload',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/wblvmd5y7izx0z10d1w7ga7zc4apjxmb-python3.11-setuptools-75.1.1/lib/python3.11/site-packages',
 '/home/runner/workspace']
Server time:	Sun, 04 May 2025 00:46:38 +0000
Traceback Switch to copy-and-paste view
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py, line 105, in _execute
                return self.cursor.execute(sql, params)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ â€¦
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py, line 360, in execute